### PR TITLE
Updated code to use openCV v4 and gave the right flags to Clang

### PR DESCRIPTION
**Pull request by sarafalamaki**
openCV used to prefix a lot of constants with "CV_". This has been removed with the addition of the cv namespace. I changed all the constants over so it works with openCV version 4. I've compiled and run it successfully on MacOS Catalina.

### CODE REVIEW

**Comment by mika-nt28** [comment]
I use opencv4 for an other project.
This pull interess me

**Comment by matthill** [comment]
Looks great!  Thanks, Sara

**Comment by mbissell** [comment]
No longer complies on successfully on ubuntu 14.04.01. Since this merge.

**Comment by joshuar87** [comment]
Hi guys, are we all good to run opencv4 and openalpr 2.3.0 on the lastest master branch? (Or should one install dev?)

**Comment by dhcmega** [comment]
@joshuar87 hi, i cannot compile.

**Pull request merged**
