### PR TITLE
comment out some code look like unused.

### PR DESCRIPTION
**Pull request by SunAriesCN**
I don't think the variable "isOn"  has a special change at this line.

### CODE REVIEW

**Comment by Silex** [comment]
IMHO if the code is really meaningless it'd be removed, not commented out.

**Comment by SunAriesCN** [comment]
I'm just not sure about it, so I just comment out here....

**Comment by Silex** [comment]
Well if you make a PR it's meant to be merged no? If it's merged, then it should not be commented out but removed...

If the merger decides that this code should not be removed then he simply does not merge it.

**Comment by matthill** [comment]
Thanks for catching that, Sun.  That char mask function was wasting cycles.

**Pull request merged**
