### PR TITLE
added Singapore license plates

### PR DESCRIPTION
**Pull request by nglinh**
Adding trained OCR and pattern regex for Singapore plates. Using eu detector.

### CODE REVIEW

**Comment by matthill** [comment]
I'd love to include this.  Is it possible to upload the character tiles for the OCR training (similar to what was done for gb: https://github.com/openalpr/train-ocr/tree/master/gb )?  The characters are binarized and separated from the plate, so there shouldn't be any privacy issues.

Otherwise, as soon as the Tesseract version changes, I'd have to pull sg out of the library.

**Comment by nglinh** [comment]
Sure thing! I have already uploaded the chars to ftp server, but will do a pull request separately on the train-ocr repo.




The number of files will be humongous though. Not sure if that’s manageble


—

**Comment by matthill** [comment]
Excellent.  I found the char tiles on the FTP and downloaded them.  Thanks for uploading that.  Overall it looks very good.  I did notice a variation of the main font included in there.  For example, these characters are from different fonts:

3-0-sgimg_20150923_140658
3-0-sgimg_20150923_140730

You would get better accuracy by splitting out these two fonts into separate font files.  Deleting the less common font would also give you better accuracy.

**Comment by nglinh** [comment]
Oh yea sorry I missed that. The upper font should be more prominent. The 2 most confusing letters for me is B and 8. The threshold result sometimes are not clear enough to differentiate between the 2


—

**Pull request merged**
