### PR TITLE
Improve docker support

### PR DESCRIPTION
**Pull request by Silex**
Hello,

The current Dockerfile is a bit weird IMHO. It just setup some dependencies but doens't do anything. It uses a custom `sources.list` that looks almost like the default one and a `trusted.gpg` that I guess is the one required to install the openalpr .deb but without the sources.list entry it's seems rather useless.

This Dockerfile builds openalpr and sets `alpr` as the entry point, which allow you use it in a very simple manner:

``` shell
# Build docker image
docker build -t openalpr https://github.com/openalpr/openalpr.git
# Download test image
wget http://plates.openalpr.com/h786poj.jpg
# Run alpr on image
docker run -it --rm -v $(pwd):/data:ro openalpr -c eu h786poj.jpg
```

To run `alprd` instead just change the entrypoint, and if you want to use it for dev also simply change the entrypoint to `bash` and cd into `/srv/openalpr`. In the future maybe multiple Dockerfiles would be desirable (Dockerfile.dev, Dockerfile.alpr, Dockerfile.alprd, etc).

### CODE REVIEW

**Comment by matthill** [comment]
Yes, you're right.  I'll get rid of those files (sources.list and trusted.gpg) since I'm not sure what they're used for either.

**Comment by Silex** [comment]
:+1:

**Comment by edwardmp** [comment]
Can you please show how one can run the deamon (alprd) with docker? Thanks

**Comment by Silex** [comment]
@edwardmp: I'd guess `docker run -it --entrypoint alprd openalpr` ?

Well, back when this image was created `alprd` did not exist. It probably makes sense to improve the image now... can you explain a bit how `alprd` works?

https://github.com/openalpr/openalpr/wiki/OpenALPR-Daemon-(alprd) is not very descriptive... usually daemons are simply started using some `-d` flag, but on this project it seems different.

**Pull request merged**
