### PR TITLE
sort eu-patterns by country

### PR DESCRIPTION
**Pull request by steffkes**
Starting out to work with openalpr, using it to recognize license plates mostly from countries based in europe.

This is hopefully just my first PR :) having those countries sorted alphabetically, makes it a bit easier to get started and seeing if there are already any patterns for a certain country

### CODE REVIEW

**Comment by matthill** [comment]
Thanks for this submission.  Putting the countries in alphabetical order definitely makes sense.  Although, I don't think we should do a simple sort, since the order of the patterns within the country does matter.  The more common plate pattern for the country should be first, and the less common ones lower.  For example:

bb @@@@
al B@@@
al A###
al C@#@

Moving the entire "al" gruop above bb is fine, but reording within the al group would cause different results.  

More explicitly:

Good:
al B@@@
al A###
al C@#@
bb @@@@

Not ideal:
al A###
al B@@@
al C@#@
bb @@@@

**Comment by steffkes** [comment]
thanks @matthill i didn't think about that, my bad. i gave it another try, sorted the patterns by country but kept the order of the existing patterns within each country as they have been.

what i'm curious while working on it, are mainly two things:
1. does it make sense to have a blank line between countries? would make it even easier to recognize the data within those pattern files. probably not just a question of _does it make sense_ but perhaps as well of _does the code accept blank lines in the pattern file?_
2. and the other one, while trying to get a better understanding of openalpr and especially the pattern matching - would it be useful to add examples for some (or actually all?) of the patterns? the reason i'm asking, i checked the history for the eu.patterns because i can't actually make sense of one of the `ch` patterns: `ch	[APM]######` as far as i know, those are not really matching any license plates in switzerland, do they? When i did live in switzerland, they basically all look like that one: https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/CH_license_plate.jpg/220px-CH_license_plate.jpg having two letters as prefix (abbreviation for the canton where it was issued) and then four to six digits after that.

**Comment by matthill** [comment]
1. Yes, I think that makes sense.  It doesn't hurt to add them and should make it easier to read.
2. Yes, probably.  I originally pulled those Switzerland patterns from a site online, but it sounds like it's wrong.  Your experience (what's actually out on the street) is much better than the current value.

**Comment by steffkes** [comment]
thanks for letting me know @matthill, added blank lines between countries in the latest commit.

to ensure that this PR doesn't outgrow its initial focus i'd go with another one for the examples. if you don't mind me asking here: does the current format allow comments? using `#` or something else? if so, i'd probably start adding those for the patterns i see/use in the images i'm going to work on if that's okay with you?

**Comment by matthill** [comment]
It doesn't filter out comments -- that would cause errors in the current code.  That would be nice though.  The code would need to be updated to remove anything starting with "#" -- we could do this via Regex.

**Comment by steffkes** [comment]
got it, i'll see what i can do there. not that much c++ knowledge on my plate yet

**Pull request merged**
