### PR TITLE
Added an overload to the C# binding for reading plates from a video.

### PR DESCRIPTION
**Pull request by ddobrev**
Hello Matt,

This is not a complete pull request but rather the basis for a discussion. I have implemented my idea that we discussed a few days ago. I have added a C# method for processing video which raises an event for each frame. I have two requests to you:
1. Can you take a look and tell me if you find it general enough and otherwise appropriate to be included?
2. I haven't tested the event because it's never raised when OpenCV lacks support for FFMPEG. I don't have the time to build OpenCV on my own, and the binaries from your release are not enough - CMake requires the entire structure of an OpenCV set-up. So could you please upload somewhere your OpenCV installation? Of course, if you find the time to test it yourself and decide to merge it, that won't be necessary and I'd only need the new release to download.

Let me know if I can help further in any way.

Dimitar

### CODE REVIEW

**Comment by matthill** [comment]
Dimitar,

Yes, this seems like a good approach.  Would the C++ code need to handle threading?  It seems like it may be best if the C# client just called "start" and the C++ interface handled execution on a background thread.  C# would just receive data on the callback and could also call "stop" if needed.

I can package up my build environment for you if that helps.  It will be a few gigabytes to download.  Or I could take this code from here and bundle it into the next release (2.0.2).  It may be a few weeks before I get to it, though.  I'm planning on releasing more frequently from now on.  Probably every 6-10 weeks.

**Comment by ddobrev** [comment]
Matt,

Glad you liked it. About threading and similar, my idea is actually quite simple: replicate what you did for videos in main.cpp. In there you just loop through the frames and print the results on the screen for each one. For the C# binding I have done the same, just the printing is replaced by raising an event.

I am afraid I need this code this week, tomorrow at best. So I would suggest another way: since you have a build server, you could give me a link to your latest build after merging this code. I know that as a non-official build it might in theory be not as stable but I believe it would be good enough, besides, this approach is faster than both you uploading - me building and waiting for the new release.

Do let me know if I need to make changes to the pull.

**Comment by ddobrev** [comment]
So, Matt, what do you think about the nightly build?

**Comment by ddobrev** [comment]
Hello Matt,

I was wondering if I could ask for your help. I've updated the pull and it works well for all but a single frame - 123 in this video: http://s000.tinyupload.com/index.php?file_id=75856380909690324695 . I verified that by adding an 'if' when raising the event. It crashes with an OutOfMemoryException each time and just for this frame. I can confirm it's not really a lack of memory because when I process just this single frame - by using that 'if' - it crashes just the same. Please let me know if you'd be willing to take a look.

**Comment by ddobrev** [comment]
Never mind, it was an invalid x-coordinate - -1 - returned in the results. Still a bug but it can be easily worked around and has nothing to do with the pull. So, please consider this patch complete.

**Comment by ddobrev** [comment]
Matt,

I've updated the pull. Now the event args have a flag for cancelling.

**Comment by matthill** [comment]
Is this working properly for you?  This crashes after reading a frame for me.  Perhaps I haven't set it up correctly?  I'm using the sample eu-clip.mp4 video

**Comment by ddobrev** [comment]
I have only tested with another video. I'll try this one as well but please check if you get an invalid coordinate for some frame like I did.

**Comment by ddobrev** [comment]
No problem here. Let me give you the code I use:

using System;
using System.Drawing;
using openalprnet;

namespace ANPR
{
    public class AnprParser
    {
        public event Action<LicensePlate> LicensePlateRecognised;

        public void ParseLicensePlates(string video)
        {
            using (var alprNet = new AlprNet("eu", "", ""))
            {
                alprNet.FrameProcessed += (sender, e) =>
                {
                    if (e.Results.plates.Count > 0)
                    {
                        var points = e.Results.plates[0].plate_points;
                        var rectangle = new Rectangle(points[0],
                            new Size(points[1].X - points[0].X, points[3].Y - points[0].Y));
                        rectangle.X = Math.Max(rectangle.X, 0);
                        rectangle.Y = Math.Max(rectangle.Y, 0);
                        this.OnPlateRecognised(new LicensePlate
                        {
                            Camera = "Camera 1",
                            PlateImage = ((Bitmap) e.Frame).Clone(rectangle, e.Frame.PixelFormat),
                            Number = e.Results.plates[0].bestPlate.characters,
                            Confidence = e.Results.plates[0].bestPlate.overall_confidence / 100,
                            Time = DateTime.Now
                        });
                    }
                };
                alprNet.recognizeFromVideo(video);
            }
        }

        private void OnPlateRecognised(LicensePlate licensePlate)
        {
            var handler = this.LicensePlateRecognised;
            if (handler != null)
            {
                handler(licensePlate);
            }
        }
    }
}

**Comment by matthill** [comment]
Hmm, that crashes too.  It's probably my setup.  I have 2.0.1-dev code on this branch so I'll need to resolve some Windows compile issues first.

**Comment by ddobrev** [comment]
I see. I use you build environment, and being lazy, I didn't even compile anything (except the binding itself, of course). I used the libs in your package instead.

**Comment by ddobrev** [comment]
Any chance you save e.Frame to use later? I destroy it after raising the event, it needs to be copied if it has to be reused later.

**Comment by matthill** [comment]
Yes, sorry it was an issue on my end.  I had to fix a couple Windows compile issues that I caused since 2.0.1.

This looks great, everything worked when I tested.  I like the cancel option.  It's simple and solves the problem.  If anyone needed background processing, they can easily add it in the .NET layer.

**Comment by ddobrev** [comment]
Excellent, thank you. And don't worry about that license for commercial code you have, consider me agreed.

**Pull request merged**
