### PR TITLE
Use motion detection in analysis of video streams and video files to increase performance

### PR DESCRIPTION
**Pull request by Kees-V**
(Issue 39)
Hi Matt,
This change introduces possibility to increase detection performance by only analysing areas with motion. I hope you like it.
There is one issue I should mention:
As you may be aware I use OpenALPR with OpenCV 3.0 RC. The OpenCL behavior can be "adjusted" before execution by setting the environment variable OPENCV_OPENCL_DEVICE.
- OpenALPR  with motion detection works fine without use of OpenCL (set OPENCV_OPENCL_DEVICE=:qqq)
- OpenALPR  with motion detection works fine with OpenCL on the CPU (set OPENCV_OPENCL_DEVICE=:CPU)
- OpenALPR  with motion detection has issues in combination with a GPU.
The cascade gives strange output with OpenCL on the GPU (set OPENCV_OPENCL_DEVICE=:GPU:0). This is surely an OpenCV issue, but may not be too bad: the performance inprovement of motion detection is less relevant in the case of GPU anyway.

Kind regards,
Kees

### CODE REVIEW

**Comment by Kees-V** [comment]
Hi Matt,
As you can see the Travis build fails.
Probably motiondetector.cpp should be added to the make file for video.lib, but I am not sure about it.
Can you please look into that,?
Kees

**Comment by matthill** [comment]
This looks really cool.  I can't compile it though with OpenCV 2.4.x, was this written for OpenCV 3?  If so, we may have to wait until the project is ready to move to OpenCV 3.  That will probably be soon after the OpenCV 3.0 release candidate becomes official.

**Comment by Kees-V** [comment]
Hi Matt,
Indeed there is a change in the OpenCV API, I am sorry I did not notice that.
I have updated motiondetector.cpp now to be compatible with OpenCV 2.4.10 (and I messed around a bit with Github...). Could you have another try on compiling?
Kind regards,
Kees
PS For your information: I discovered that currently there is an issue in the OpenCV release numbering that makes it difficult to make a sensible #if #elif

**Comment by Kees-V** [comment]
Motion detection also applicable to the webcam...

**Comment by robertocarvajal** [comment]
I use #if CV_MAJOR_VERSION == 2 to condition the opencv api calls, can you try with that?

**Comment by matthill** [comment]
I'm seeing an OpenALPR bug when I test this.  I'm going to fix that first and then merge this in.  The motion detection seems to be working well.

**Pull request merged**
