### PR TITLE
New detector based on morphological operators

### PR DESCRIPTION
**Pull request by LordF**
New plate detector

### CODE REVIEW

**Comment by matthill** [comment]
Fredi,

Great work!  I pulled the code down and compiled it and ran a few tests.  It looks good.  I bet it works especially well for European plates with infrared cameras.  The biggest advantage seems to be speed, and the fact that it doesn't require training.  It didn't work well at all with visible light US plates, but that's expected.

One thing that would probably help narrow down the false positives is a simple aspect ratio test.  In the example below, only one of those boxes could realistically have a plate, the others are taller than they are wide. 


If you haven't already done so, please review and agree to the project's Contributor License Agreement (CLA).  It allows me to relicense the software.

I'll also make some changes to hook this into the configuration so that users could choose what detector they wish to use.

**Comment by LordF** [comment]
Ok Matt,
I will try to improve this detection. Also it lacks support for different types of plates like white on dark plates. Anyway, I will work on that as well.

**Comment by matthill** [comment]
If you can agree to the CLA, I can merge this code as-is and call it "experimental."  I'm sure many folks will find this useful in its current form.  We can add enhancements in the future.

**Comment by LordF** [comment]
I did agree already. Let me know if there is something wrong. By the way, I made some enhancements regarding the aspect of the detected rectangles.I will commit after the Code is accepted.

Enviado do meu iPhone

**Comment by vladimirr0708982** [comment]
I think will be good in "config" to be options what algoritam to use for detection.... like for GPU

**Comment by matthill** [comment]
Excellent, this looks good.  I integrated this with the configuration and merged it to the latest.  I noticed a crash when I ran against a large number of images -- sometimes the regions were outside of the image area.  So I applied that small fix before pushing.

**Pull request closed without merging**
