### PR TITLE
Initialize scale_factor separately for every picture separately

### PR DESCRIPTION
**Pull request by Kees-V**
When alpr is used with a series of pictures of different sizes scale_factor needs to be calculated or set to 1 for every picture separately. 
A small picture processed after a large picture should be analysed with scale_factor = 1.

### CODE REVIEW

**Comment by Kees-V** [comment]
Check detected plate region before using it to avoid occasional "OpenCV Error: Assertion failed"

**Comment by matthill** [comment]
Do you have a test image (and perhaps associated parameters) taht cause the second issue (Assertion Failed)?

I'm planning on fixing the scale factor problem by making scale_factor a function level parameter -- it doesn't need to be private in the class.

**Comment by Kees-V** [comment]
A clarification of the first issue:
This issue shows when going through a series of images in a directory (e.g. commandline: “alpr  . “)
scale_factor is currently only re-calculated if frame.cols > config->maxDetectionInputWidth or frame.rows > config->maxDetectionInputHeight.
As a result a small image which follows a large image in a directory is scaled down with the scale_factor of the previous large picture.

About the second issue:
I sent you a direct email with a test image and the config file to illustrate the second issue, using a compile of the latest alpr-source
Commandline:
“alpr -c eu -p nl laststill.bmp”

Kees

**Comment by matthill** [comment]
I wasn't able to reproduce that second issue with the image you sent me... not sure why.

**Comment by Kees-V** [comment]
Hi Matt,
Thanks for your response.
I think the issue is related to my use of OpenCV 3.0. 
After my pull request I downloaded release the OpenALPR 2.0.1 binary (with OpenCV 2.4.8). 
I can't reproduce the issue with the 2.0.1 binary and any of my test material.
So... the second issue (currently) does not exist. I am sorry for bringing it up.
Kees

**Comment by matthill** [comment]
Not at all -- I appreciate you letting me know about it... it may be an issue but just due to randomness and changes between your setup and mine it doesn't show up for me.  These intermittent problems are very tricky to tackle!

**Pull request closed without merging**
