### PR TITLE
Reduce the times for this loop

### PR DESCRIPTION
**Pull request by SunAriesCN**
After the modification, I think the loop will break if pxLeniency is large enough.

### CODE REVIEW

**Comment by matthill** [comment]
I think it already kicks out here before looping too many times:
https://github.com/openalpr/openalpr/blob/master/src/openalpr/segmentation/charactersegmenter.cpp#L317

Changing the pxLeniency changes the logic, rather than just a speed increase.  I tweaked the function to be a little faster in this commit:
https://github.com/openalpr/openalpr/commit/cced283f1eb9fd1a42edbd788956daef542d830d

 although it's still quite fast either way (< 0.5ms processing time)

**Comment by SunAriesCN** [comment]
I don't think so, and I think the loop of row is nonsense here, because the pxLeniency is always 0 here so that results for each loop must be always the same. So, I change that line there, the logic may need to be changed.

**Comment by matthill** [comment]
I took another look at it, sorry I misunderstood.  You're right, that loop was not even being used.  Thanks for the fix and helping me understand correctly.

**Comment by SunAriesCN** [comment]
You're welcome.

**Pull request merged**
