### PR TITLE
Add function header

### PR DESCRIPTION
**Pull request by LordF**
Added missing function header

### CODE REVIEW

**Comment by matthill** [comment]
Excellent.  Thanks for adding this -- the extra size filter does seem to make a difference.  I merged in the changes w/ the other pull request.

**Comment by LordF** [comment]
Nice, sorry for the mess. Matt, I think we could use some ideas in order to
improve the detection before the character analysis. If we could somehow
use the skew angle of the rect to deskew before trying to do the analysis.

2015-03-21 11:30 GMT-03:00 Matthew Hill <notifications@github.com>:

**Comment by matthill** [comment]
Yes, there's so many possibilities.  There's lots of research papers out there about license plate detection.  Perhaps something related to text detection: http://www.mathworks.com/help/vision/examples/automatically-detect-and-recognize-text-in-natural-images.html

For example, combining the region detected w/ morphology with stroke-width detection should allow the morphology to be a bit more lenient (catching more plates) and ruling out false positives by making sure that there is valid-looking text inside.

The skew of the plate is handled in the platelines/platecorners phase.  It tries to find strong edges to identify the corners, and then remaps it to the right dimensions with a perspective transformation.

**Comment by LordF** [comment]
Nice referentes. I already heard about stroke width transform. By the Opencv hás a new module to detect text in scene images based on mser, haven't tried it yet though.

Enviado do meu iPhone

**Pull request closed without merging**
