### PR TITLE
Add multi-thread frame processing to daemon.

### PR DESCRIPTION
**Pull request by sam-dieck**

### CODE REVIEW

**Comment by matthill** [comment]
Sam, thanks for this contribution.  The code looks good to me.  It looks like it requires C++11 to compile.  Is it possible to support C++98?  I ask because there's a number of folks running this on hardware that must be built with older compilers.

**Comment by sam-dieck** [comment]
Hey Matt, ... probably yes, let me look into it.

**Comment by sam-dieck** [comment]
Hey Matt,

c++98 doesn't have any support for threading in the standard library... however I just realized that TinyThread (the current c++98 compatible library that openalpr is using for threading) does have a mutex and a condition variable available.

I will change the current SafeQueue implementation to use TInyThread's types.

Let me know if you have a better idea or any other comment.

Thanks
Sam

**Comment by matthill** [comment]
Thanks, Sam.  Looks great!

**Pull request merged**
