### PR TITLE
Fix for undefined symbol: recognizeRawImage in Python binding #533 

### PR DESCRIPTION
**Pull request by ebadi**
Fix for #533, removing binding for `recognizeRawImage`  method that is non-existent. (as mentioned in https://github.com/openalpr/openalpr/issues/533#issuecomment-782746702  )
Very similar to pull request #953 by @cclauss that is not yet merged. Sorry for spamming [everyone here](https://github.com/openalpr/openalpr/commits/master/src/bindings/python) (@matthill @tweej @tgandor @robinhilliard @peters ) since it is not clear who has access and expertise to review and merge this.

### CODE REVIEW

**Comment by cclauss** [comment]
My sense is that https://www.openalpr.com is a paid product so this original codebase is no longer maintained so that there is incentive to purchase access.

**Comment by ebadi** [comment]
@cclauss  You are right. The last commit is on Jul 30, 2020. I am more than happy to contribute my code to any other commercial or non-commercial fork of the project. (is there such a fork?).  For now I started a fork, [openalpr-plusplus](https://github.com/ebadi/openalpr-plusplus) to fix this issue and add new features for my small use-case.

**Comment by cclauss** [comment]
@ebadi Why continue with this PR?  This repo is no longer updated.

**Comment by ebadi** [comment]
Sure, closing this PR.

**Pull request closed without merging**
