### PR TITLE
.NET Binding

### PR DESCRIPTION
**Pull request by peters**
/cc @matthill

### CODE REVIEW

**Comment by peters** [comment]
@matthill In order to support video capture in the .NET binding (from a mjpeg stream) it would be probably best to move code found in `main.cpp` in alpr executable to `AlprImpl` so that i can reuse those bits. Right now we have support for capturing mjpeg streams but i'd rather use opencv for this.

**Comment by matthill** [comment]
I merged all this code (missed the last two commits).  I changed the name of the debugOff to setDebug, and also pulled the includes out of config.h and put them in config.cpp.  

That should make it easier for people to pull that in and use the Config object without getting forced to pull in a bunch of unnecessary dependencies.

**Comment by matthill** [comment]
Yeah, that's a good idea.  I have the "video" library where most of that code resides.  I haven't tested it on Windows, though, since it's just used in the alpr daemon.

**Comment by peters** [comment]
@matthill I'm going to begin the testing the nuget package now, and if everything is okay, you should publish the package to `nuget.org`. The only thing that's missing is support for using the nuget package in c++ projects on Windows. 

Btw, do you want to have separate nuget packages for cuda? The release build is roughly 34MB with CUDA support, 20MB without.

**Comment by peters** [comment]
The nuget package is now working properly. With and without CUDA! wooho :dancers:

**Comment by matthill** [comment]
Excellent!  I think 34MB is perfectly reasonable.  I'll need to take some time to figure out nuget and the automated build service you mentioned.  That would make it much easier to push releases more frequently.

**Comment by peters** [comment]
> Excellent! I think 34MB is perfectly reasonable.
One can save a few megs if you only embed the required opencv* dependencies, so i totally agree.

> I'll need to take some time to figure out nuget and the automated build service you mentioned
:+1:

**Pull request merged**
