### PR TITLE
Added font based bonus score for better accuracy

### PR DESCRIPTION
**Pull request by doodhwala**
Addressing the following issue:
https://github.com/openalpr/openalpr/issues/22

### CODE REVIEW

**Comment by doodhwala** [comment]
For some reason, even though I changed 30-40 lines, it is showing up as 500 changes
I need to look into this.

**Comment by vladimirr0708982** [comment]
I think is in result_aggregator.cpp u erase add "same" txt all.... now just changes

**Comment by doodhwala** [comment]
@vladimirr0708982 
I copy pasted the latest version of results_aggregator.cpp and committed
But the changes add up instead of the modifications cancelling each other out

**Comment by matthill** [comment]
Hi Doodhwala,

Thanks for this contribution!  It's a great idea.  I suspect with some refinement it may improve accuracy in OpenALPR.

Unfortunately right now it seems to lower the accuracy numbers when run against my benchmarks.

Here's the before and after for the European plate benchmark (https://github.com/openalpr/benchmarks/tree/master/endtoend).  I see slightly more pronounced decrease with my US benchmarks.


**Summary Before:**
Accuracy scores (higher is better)
Percent of plates DETECTED: 99.0741
Percent of correct TOP10:   92.5926
Percent of correct MATCHES: 75.9259

False Positives Score (lower is better)
False DETECTIONS per image: 0.0925926
False RESULTS per image:    0.0740741

**Summary After**
Accuracy scores (higher is better)
Percent of plates DETECTED: 99.0741
Percent of correct TOP10:   91.6667
Percent of correct MATCHES: 70.3704

False Positives Score (lower is better)
False DETECTIONS per image: 0.0925926
False RESULTS per image:    0.0833333

**Comment by doodhwala** [comment]
Hi Matthew,
    I shall look into this tomorrow. I have an idea on how to improve it (theoretically) and it is just a matter of fine tuning it and putting it into code. Thank you for running the benchmark tests.

**Comment by matthill** [comment]
If you find time to look at this again, please open a new PR.  Thanks, @doodhwala  :)

**Pull request closed without merging**
