### PR TITLE
Update platemask.cpp

### PR DESCRIPTION
**Pull request by SunAriesCN**
I think the outer box you want here is from which the outer contour has most of characters inside, rather than just the last outer contours of characters in threshold image as before codes. I study your codes theseday, and would like to share my thought wit you. How can I contact you?

### CODE REVIEW

**Comment by matthill** [comment]
You can get me on IRC (#openalpr) or gchat (matthill@openalpr.com)

I ran these changes against my benchmarks -- the results are still the same.  This I'm wondering if this function is being called...

**Comment by SunAriesCN** [comment]
Did you run the benchmarks/seg_and_ocr only? By the way, I think it may be a occasional problem, and  a little bit difficult to reveal this problem. But I think I can manipulate an image sample  to test  your program-flow, without the doCascade detection part, to recur the problem. Because when I read the codes of this part carefully, I found that you let the last outer contours to be the outer-box mask, and confused whether it is your orignal idea. And if it is, could you mind give me the reason about that?

**Comment by matthill** [comment]
I ran the endtoend benchmark.  I'm wondering if that section of the code is never getting called or if the results don't get used.  Perhaps those bugs I made were never noticed because the function is not used. 

The original idea for the function was to find a rectangular-ish region that contained most of the plate characters.  These didn't often exist, but when they did they were helpful for determining at least some of the edges of the plates.  I don't think it was my intention to use the last contour as the outer mask.

Do you have a before/after image I can run against to see the effect?

**Comment by SunAriesCN** [comment]
I have sent you two photos on mail.

**Comment by matthill** [comment]
Thanks, Sun!

**Pull request merged**
