### PR TITLE
Fix ifs that were always true

### PR DESCRIPTION
**Pull request by araml**

### CODE REVIEW

**Comment by matthill** [comment]
Are you sure this is right?   According to the docs, if the character is not found it should return npos:
http://en.cppreference.com/w/cpp/string/basic_string/find_last_of

**Comment by araml** [comment]
Sorry if I'm not following you, but if the return value is not npos then it found the character thus you can return the substr. At least thats why I understood the old code tried to do.

**Comment by Silex** [comment]
``` c++
 if (found != std::string::npos)
        return file_path.substr(found + 1);
```

That looks correct to me.

`If variable is different than was is used to indicate "not found", then return data`

**Comment by matthill** [comment]
Gah, sorry, I was reading the PR backwards :)  Yes, using a constant rather than a magic number is correct.  Thanks, Araml!

**Pull request merged**
