### PR TITLE
Recognize numpy image

### PR DESCRIPTION
**Pull request by corentin87**
**Goal**
The OpenALPR Python binding interface currently only has a couple of methods in the binding to process images for number plate recognition. The provided methods either take a file to an image or an array of bytes which represent a jpeg image. It would be great to be able to pass in an OpenCV image (numpy array) so that the conversion to JPEG from numpy would not be required.

**Change**
include a new method that takes a numpy array and performs a number plate recognition

### CODE REVIEW

**Comment by matthill** [comment]
Another merge request for the same feature came in around the same time.  Can you take a look at this one: https://github.com/openalpr/openalpr/pull/498 

Does that solve the same issue for you?

**Comment by corentin87** [comment]
Yes it does the same thing. The code is actually really similar. I found it a weird that the other pull request happened 4 hours after mine actually.

**Comment by matthill** [comment]
Yes, so did I.  I thought you might know each other :)

**Comment by corentin87** [comment]
Not at all, but this is open source anyway!

**Pull request closed without merging**
