### PR TITLE
TopN values strange behavior #135

### PR DESCRIPTION
**Pull request by psaintjust**
Attempt #2 - this time with significant refactoring

**Original issues**
* There was a bug in the pruning that could lead to incorrect results for permutations 3 and higher.  The permutations were not being traversed in scoring order while being removed (topN check)
* The check for min/max characters was happening too late and could cause the number of results to be less than topN.

**Changes**
* The refactored code combines the pruning, possibility generation, sorting and template matching into a single pass:
  * findAllPermutations - loops through each permutation in scoring order using a priority queue.  For each permutation, it calls analyzePermutation.  The loops stops once topN possibilities have been identified.
  * analyzePermutation - generates the possibility, checks for min/max characters, checks against the template (if provided), avoids duplicates (e.g. [space][b] vs [b][space]).  If all conditions are met, the possibility is added to the result list.

+ Removed postprocess_max_substitutions configuration option since it supported the original pruning logic.

+ Changed recursive logic to iterative.

### CODE REVIEW

**Comment by matthill** [comment]
Excellent, this is a significant improvement.  Thanks, Philippe.

I confirmed that this resolves issue #97 and probably also resolves issue #135 -- but I don't have a reliable test for that one.

I ran my benchmarks before and after, and noticed a > 1% improvement in top10 accuracy!

*BEFORE*
Percent of correct TOP10:   **72.5225**
Percent of correct MATCHES: 54.955

*AFTER*
Percent of correct TOP10:   **73.8739**
Percent of correct MATCHES: 54.955


I ran it against a few thousand images, and I only found a handful that were slow -- almost all the images processed in < 1ms.  I definitely plan on merging these changes, but just wondering if you want to take a look at this image that was 115ms or so (~500x slower than others).

test_067

I think it's the grill of the car that's causing the stutter.

**Comment by psaintjust** [comment]
Hi Matt,
The image you sent generates two potential license plates.  The slow one is the grill: 18 letters mostly "I"s.  The logic goes through all permutations ultimately rejecting all of them because of the max character length - that's where the performance impact is.

In the original code, since you're not taking into account word length while you're pruning.  You stop after 10 permutations.  Need to add something here to limit the amount of permutations with no valid results probably.

**Comment by robertocarvajal** [comment]
finally, I have a very slow detection on some cases because of that, I knew that a grilled fence detected as IIIIIIIIII but it never clicked for me that it was the case for the slow performance.. so, I guess adding grill images to the negative set and retraining should improve that?

**Comment by matthill** [comment]
Yes, grills and fences (and any false positives) will definitely slow you down, just because they need to be processed (may add 35ms or so each).  Sometimes they make it through all the processing stages and give you results like 11L1L1D

This fix isn't related though.  Before Phillipe made any changes, the postprocess was relatively fast (even for fences and grills) but the topN accuracy was poor.  After his changes, he seems to have made it slightly faster, and the accuracy is 100% correct.  The slow processing for the grill was the only performance issue I found and he fixed that before merging.

**Pull request merged**
