### PR TITLE
Improve windows build experience

### PR DESCRIPTION
**Pull request by peters**
Matt,

For us, windows needs to be a "first class citizen" in your build matrix. So I've created a separate repository @ https://github.com/peters/openalpr-windows which contains all the source dependencies for building openalpr on Windows "the easy way". Support for nuget will follow shortly.

This change makes it really easy consuming the latest OpenALPR bits on Windows :+1:

### CODE REVIEW

**Comment by peters** [comment]
Bonus points:

* OpenALPR fork's this repository 
* Build automation using AppVeyor

**Comment by peters** [comment]
Nuget support has now been added.

**Comment by matthill** [comment]
This is awesome.  I played around with the Powershell script -- it's a big improvement over what I was doing.  

I'm merging all these changes, thanks for adding them.  I removed one unused compile flag (WITH_ALPR_STATICALLY_LINKED)

**Comment by peters** [comment]
:+1:

**Pull request merged**
