### PR TITLE
Add new enhancements

### PR DESCRIPTION
**Pull request by LordF**
Add few enhancements

### CODE REVIEW

**Comment by Silex** [comment]
These commits are kinda "ugly". You'd squash them together, also you'd close #91 and put its changes in this PR.

**Comment by LordF** [comment]
Ok i will fix it

**Comment by matthill** [comment]
This doesn't compile for me.  I think it's missing the header file changes.

**Comment by LordF** [comment]
Matt,
I will try to see what's going on, commited it a few days ago but I'm
unable to see the changes

2015-03-21 10:19 GMT-03:00 Matthew Hill <notifications@github.com>:

**Comment by LordF** [comment]
I just made a pr to fix the missing header https://github.com/openalpr/openalpr/pull/93

**Pull request merged**
