### PR TITLE
.Net (C++/CLI) Wrapper for OpenAlpr

### PR DESCRIPTION
**Pull request by masroore**
.Net wrapper for openalpr c.f. #68 
Platform: WIN32, .NET4.0
VS2010 Update 1

openalpr-net.dll (mixed-mode C++/CLI wrapper) 
openalprnet-cli.exe (C#)

### CODE REVIEW

**Comment by matthill** [comment]
Very nice!  People would find this extremely helpful.  This is one of the more frequently requested features.

Before I can merge, can you agree to the project's CLA?
https://www.clahub.com/agreements/openalpr/openalpr

I need that so that I am able to relicense the project

**Comment by masroore** [comment]
@matthill Thanks!

I agree to the CLA. (Tried to sign up with clahub.com but the website is throwing error at the moment.)

Feel free to merge and relicense these 2 projects.

**Comment by matthill** [comment]
Excellent.  Thanks, Dr. Ehsan.  I'll pull the code, run a quick test, and merge it in tonight.

**Comment by matthill** [comment]
I pulled the code tonight, and noticed that it works great for the 1.2 API, but not the new 2.0 API.  Before I merge it into master, I'll need to get it updated.  The changes seemed fairly minor. 

I resolved all of the Windows compile issues on the latest code.  

I started updating the bindings -- I changed the variables to get it to compile, but when I ran the C# program, it doesn't work.  It quickly eats up memory until it crashes.  I added a bug in there somewhere.  The latest commit is on a separate branch (openalpr-net) here: https://github.com/openalpr/openalpr/commit/4f3c768b0fef1de23f47ab251c793a581e97b829

**Comment by masroore** [comment]
I have updated the binding for v2.0 here: #71

However, it seems the following methods are not working properly in the latest version:
```
AlprResults recognize(std::string filepath);
AlprResults recognize(std::vector<char> imageBytes);
```
Only the following method is able to recognize the plates:
```
AlprResults recognize(unsigned char* pixelData, int bytesPerPixel, int imgWidth, int imgHeight, std::vector<AlprRegionOfInterest> regionsOfInterest);
```

I have updated the C++/CLI wrapper methods to utilize the 3rd API.

**Comment by matthill** [comment]
Nice.  Yes, it looks like those are not working due to a bug that I caused (recently) by implementing the RegionsOfInterest.  I fixed the 2.0 API in the latest code and merged with your branch.  Everything seems to be working perfectly.

In the future, I'll plan to compile a .NET dll with every major release.

**Pull request merged**
